### PR TITLE
Use whereIn instead of raw, get foreignKey correctly

### PR DESCRIPTION
**Pull request by dominicbartl**
`relatedData.foreignKey` is null. I replaced it with `key('foreignKey')` to get the foreign key. You also used the rawWhere function and formatted the where clause with some single and double quotes which don't work with mysql.

### CODE REVIEW

**Comment by renarsvilnis** [comment]
Also struggling on MySQL due to the `rawWhere` usage, while debugging knex the foreign-key seems wrongly escaped: `(\'26\')`.

``` javascript
{ method: 'del',
  options: {},
  timeout: false,
  bindings: [],
  sql: 'delete from `item_biodata_select_option` where "select_id" IN (\'26\')' }
{ method: 'del',
  options: {},
  timeout: false,
  bindings: [ 26 ],
  sql: 'delete from `item_biodata_select` where `id` = ?' }
```

But now on this PR seems failing on postgre.

**Comment by ricardogama** [comment]
@renarsvilnis Working on **MySql** support for this plugin.

**Comment by renarsvilnis** [comment]
Just updated tests to mysql work. Will make a PR.

**Edit:** check #6

**Comment by ricardogama** [comment]
Thank you guys for your contributions!

I've been investigating the issues you detected with the **MySQL** client and just opened #7 with a rough solution, feel free to try it out and review.

I realised that what was being wrongfully wrapped was the dependent key, not the use of `whereRaw` nor the value of `parentValue`. Also, I decided to refactor all the test suite to cover both **PostgreSQL** and **MySQL** clients as @renarsvilnis suggested on #6.

@Bartinger I couldn't reproduce the error you got using `relatedData.foreignKey` instead of `relatedData.key('foreignKey')`. Can you tell me what versions of **bookshelf**, **knex** and **node-mysql** you used?

**Comment by dominicbartl** [comment]
@ricardogama I think when you don't explicetly set the foreign key and use the default naming strategy (table_id) `foreignKey` will be undefined and `key('foreignKey')` generates the correct key. I pulled your feature/mysql-support branch and tried it out and added a new table without specifically defining the foreign key.
Though now there seems to be a case sensitive error with postgres. You can take a look at it here. 
https://github.com/Bartinger/bookshelf-cascade-delete/blob/feature/mysql-support/src/index.js

**Comment by ricardogama** [comment]
@Bartinger Just pushed a new fix, can you pull and try it out again?

**Comment by dominicbartl** [comment]
@ricardogama I already pulled the latest changes. I merged f6478e2

**Comment by ricardogama** [comment]
You need to rebase until [59e013c](https://github.com/seegno/bookshelf-cascade-delete/pull/7/commits/59e013cad0dad0200222b63478ad6eb9d60a7792), all good then?

**Pull request closed without merging**
